Repository AztecGameLab/LongTermGame4, pull requests merged in 2020-11, with the labels that each got.

#145 Unity event modularity
  Assets/AmplifyShaderEditor.meta
  Assets/Audio/Arrows/Collisions/Anti-Gravity.meta
  Assets/Scenes/ArrowTriggerTesting.unity
  Assets/Scenes/CombinedScene.unity
  Assets/Scripts/ArrowTrigger.cs
  Assets/Scripts/EventTrigger.cs
  Assets/Scripts/EventTrigger.cs.meta
  Assets/Scripts/EventTriggeredIndicator.cs
  Assets/Scripts/EventTriggeredIndicator.cs.meta
Labels: enhancement

#144 Reload Level
  Assets/Audio/Arrows/Collisions/Anti-Gravity.meta
  Assets/Audio/Arrows/Collisions/Anti-Gravity/AGL Reverse-Gravity Arrow Effect Loop.wav.meta
  Assets/Audio/Arrows/Collisions/Anti-Gravity/AGL Reverse-Gravity Arrow Effect Start+Stop.wav.meta
  Assets/Audio/Arrows/Collisions/Anti-Gravity/AGL Reverse-Gravity Arrow Effect Start.wav.meta
  Assets/Audio/Arrows/Collisions/Anti-Gravity/AGL Reverse-Gravity Arrow Effect Stop.wav.meta
  Assets/Bow and Arrow.meta
  Assets/Prefabs/Player.prefab
  Assets/Scripts/ReloadScene.cs
  Assets/Scripts/ReloadScene.cs.meta
  Assets/Textures.meta
  Assets/Textures/UI.meta
  Assets/Textures/UI/arrow-graphic-background.png.meta
  Assets/Textures/UI/arrow-graphic-energy-bar.png.meta
  Assets/Textures/UI/arrow-graphic-lineart.png.meta
  Assets/Textures/UI/arrow-graphic-vines.png.meta
Labels: enhancement

#154 antigrav arrows and fixed arrow rotation
  Assets/Audio/Arrows/Collisions/Anti-Gravity/AntiGrav.asset
  Assets/Audio/Arrows/Collisions/Anti-Gravity/AntiGrav.asset.meta
  Assets/Prefabs/Arrows/AntiGravArrow.prefab
  Assets/Prefabs/Arrows/AntiGravArrow.prefab.meta
  Assets/Prefabs/Arrows/ArrowCombined.prefab
  Assets/Scenes/CombinedScene.unity
  Assets/Scripts/AntiGrav.cs
  Assets/Scripts/AntiGrav.cs.meta
  Assets/Scripts/AntiGravArrow.cs
  Assets/Scripts/AntiGravArrow.cs.meta
  Assets/Scripts/ArrowRotation.cs
  ProjectSettings/QualitySettings.asset
Labels: enhancement

#155 Added Timer + Gauntlet Functionality
  Assets/Materials/green.mat
  Assets/Materials/green.mat.meta
  Assets/Scenes/PickupObjects.unity
  Assets/Scenes/Timer.unity
  Assets/Scenes/Timer.unity.meta
  Assets/Scripts/Timer Scripts.meta
  Assets/Scripts/Timer Scripts/ExampleTimerController.cs
  Assets/Scripts/Timer Scripts/ExampleTimerController.cs.meta
  Assets/Scripts/Timer Scripts/GauntletController.cs
  Assets/Scripts/Timer Scripts/GauntletController.cs.meta
  Assets/Scripts/Timer Scripts/Timer.cs
  Assets/Scripts/Timer Scripts/Timer.cs.meta
  Assets/Textures.meta
  ProjectSettings/Packages/com.unity.probuilder/Settings.json
Labels: enhancement

#142 Added Stop Pull enhancement and fixed non-rigid pull bug
  Assets/Scripts/GrapplingArrow.cs
  Assets/Scripts/PlayerShooting.cs
Labels: enhancement

#156 Movement stuff
  Assets/Audio/Movement/Footsteps.meta
  Assets/Audio/Movement/Footsteps/stone footstep 1.wav
  Assets/Audio/Movement/Footsteps/stone footstep 1.wav.meta
  Assets/Audio/Movement/Footsteps/stone footstep 2.wav
  Assets/Audio/Movement/Footsteps/stone footstep 2.wav.meta
  Assets/Audio/Movement/Footsteps/stone footstep 3.wav
  Assets/Audio/Movement/Footsteps/stone footstep 3.wav.meta
  Assets/Audio/Movement/Footsteps/stone footstep 4.wav
  Assets/Audio/Movement/Footsteps/stone footstep 4.wav.meta
  Assets/Audio/Movement/Footsteps/stone footstep 5.wav
  Assets/Audio/Movement/Footsteps/stone footstep 5.wav.meta
  Assets/Audio/Movement/Footsteps/stone footstep 6.wav
  Assets/Audio/Movement/Footsteps/stone footstep 6.wav.meta
  Assets/Audio/Movement/Footsteps/stone footstep 7.wav
  Assets/Audio/Movement/Footsteps/stone footstep 7.wav.meta
  Assets/Audio/Movement/Heavy Run with armor.wav
  Assets/Audio/Movement/Heavy Run with armor.wav.meta
  Assets/Audio/Movement/Heavy Walk with armor.wav
  Assets/Audio/Movement/Heavy Walk with armor.wav.meta
  Assets/Audio/Movement/Stone Stairs Run armor.wav
  Assets/Audio/Movement/Stone Stairs Run armor.wav.meta
  Assets/Audio/Movement/Stone Stairs Run no armor.wav
  Assets/Audio/Movement/Stone Stairs Run no armor.wav.meta
  Assets/Audio/Movement/Stone Stairs Walk armor.wav
  Assets/Audio/Movement/Stone Stairs Walk armor.wav.meta
  Assets/Audio/Movement/Stone Stairs Walk no armor.wav
  Assets/Audio/Movement/Stone Stairs Walk no armor.wav.meta
  Assets/Audio/Paper.meta
  Assets/Audio/Paper/Pick Up Lore Paper - Dry.wav
  Assets/Audio/Paper/Pick Up Lore Paper - Dry.wav.meta
  Assets/Audio/Paper/Pick Up Lore Paper - Reverb.wav
  Assets/Audio/Paper/Pick Up Lore Paper - Reverb.wav.meta
Labels: enhancement

#163 cloud and rock graphics
  Assets/Textures/Particles/CLOUD-GRAPHIC.png
  Assets/Textures/Particles/ROCK-GRAPHIC.png
Labels: enhancement

#166 Added Line renderer and Grappable script
  Assets/Scenes/CombinedScene.unity
  Assets/Scripts/GrapplingArrow.cs
  Assets/Scripts/IsGrappable.cs
  Assets/Scripts/IsGrappable.cs.meta
Labels: enhancement

#167 Line renderer attaches to arrow instead of object
  Assets/Scripts/GrapplingArrow.cs
Labels: bug

#178 Switch to rigidbody player movement
  Assets/.DS_Store
  Assets/PhysicsMaterials.meta
  Assets/PhysicsMaterials/Player.physicMaterial
  Assets/PhysicsMaterials/Player.physicMaterial.meta
  Assets/Prefabs/Arrows/Arrow.prefab
  Assets/Prefabs/Player.prefab
  Assets/Scenes/CombinedScene.unity
  Assets/Scripts/AntiGravArrow.cs
  Assets/Scripts/GrapplingArrow.cs
  Assets/Scripts/PlayerMovement.cs
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/TagManager.asset
Labels: bug, enhancement

#179 Created new ArrowPowerUI branch
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/ShotPowerUI.prefab
  Assets/Prefabs/ShotPowerUI.prefab.meta
  Assets/Scenes/CombinedScene.unity
  Assets/Scenes/PlayerShooting.unity
  Assets/Scripts/PlayerManager.cs
  Assets/Scripts/PlayerShooting.cs
  Assets/Textures/UI/arrow-graphic-background.png.meta
  Assets/Textures/UI/arrow-graphic-energy-bar.png.meta
  Assets/Textures/UI/arrow-graphic-lineart.png.meta
  Assets/Textures/UI/arrow-graphic-vines.png.meta
Labels: enhancement

#182 Adding in Antigravity Arrow textures and Paper Sheet
  Assets/Bow and Arrow.meta
  Assets/Materials/Antigravity Arrow.meta
  Assets/Materials/Antigravity Arrow/AGravityPoint.mat
  Assets/Materials/Antigravity Arrow/AGravityPoint.mat.meta
  Assets/Materials/Antigravity Arrow/AGravityWood.mat
  Assets/Materials/Antigravity Arrow/AGravityWood.mat.meta
  Assets/Materials/Antigravity Arrow/aGravityFrill.mat
  Assets/Materials/Antigravity Arrow/aGravityFrill.mat.meta
  Assets/Materials/Antigravity Arrow/arrow_lp_frill_AlbedoTransparency.png
  Assets/Materials/Antigravity Arrow/arrow_lp_frill_AlbedoTransparency.png.meta
  Assets/Materials/Antigravity Arrow/arrow_lp_frill_MetallicSmoothness.png
  Assets/Materials/Antigravity Arrow/arrow_lp_frill_MetallicSmoothness.png.meta
  Assets/Materials/Antigravity Arrow/arrow_lp_frill_Normal.png
  Assets/Materials/Antigravity Arrow/arrow_lp_frill_Normal.png.meta
  Assets/Materials/Antigravity Arrow/arrow_lp_point_AlbedoTransparency.png
  Assets/Materials/Antigravity Arrow/arrow_lp_point_AlbedoTransparency.png.meta
  Assets/Materials/Antigravity Arrow/arrow_lp_point_MetallicSmoothness.png
  Assets/Materials/Antigravity Arrow/arrow_lp_point_MetallicSmoothness.png.meta
  Assets/Materials/Antigravity Arrow/arrow_lp_point_Normal.png
  Assets/Materials/Antigravity Arrow/arrow_lp_point_Normal.png.meta
  Assets/Materials/Antigravity Arrow/arrow_lp_stick_AlbedoTransparency.png
  Assets/Materials/Antigravity Arrow/arrow_lp_stick_AlbedoTransparency.png.meta
  Assets/Materials/Antigravity Arrow/arrow_lp_stick_MetallicSmoothness.png
  Assets/Materials/Antigravity Arrow/arrow_lp_stick_MetallicSmoothness.png.meta
  Assets/Materials/Antigravity Arrow/arrow_lp_stick_Normal.png
  Assets/Materials/Antigravity Arrow/arrow_lp_stick_Normal.png.meta
  Assets/Materials/PaperTextures.meta
  Assets/Materials/PaperTextures/Paper.mat
  Assets/Materials/PaperTextures/Paper.mat.meta
  Assets/Materials/PaperTextures/paper_lp_lambert1_AlbedoTransparency.png
  Assets/Materials/PaperTextures/paper_lp_lambert1_AlbedoTransparency.png.meta
  Assets/Materials/PaperTextures/paper_lp_lambert1_MetallicSmoothness.png
  Assets/Materials/PaperTextures/paper_lp_lambert1_MetallicSmoothness.png.meta
  Assets/Materials/PaperTextures/paper_lp_lambert1_Normal.png
  Assets/Materials/PaperTextures/paper_lp_lambert1_Normal.png.meta
  Assets/Original Meshes.meta
  Assets/Original Meshes/Bow.fbx
  Assets/Original Meshes/Bow.fbx.meta
  Assets/Original Meshes/New folder.meta
  Assets/Original Meshes/arrow.fbx
  Assets/Original Meshes/arrow.fbx.meta
  Assets/Original Meshes/bowAnimated.fbx
  Assets/Original Meshes/bowAnimated.fbx.meta
  Assets/Original Meshes/paper_lp.fbx
  Assets/Original Meshes/paper_lp.fbx.meta
  Assets/Prefabs/AntiGravityArrow.prefab
  Assets/Prefabs/AntiGravityArrow.prefab.meta
  Assets/Scenes/BowandArrowSampleScene.unity
Labels: enhancement

#183 Basic grapple levels
  Assets/Materials/Black.mat
  Assets/Materials/Black.mat.meta
  Assets/Materials/red.mat
  Assets/Materials/red.mat.meta
  Assets/Scenes/Puzzles/GrapplePullTutorial.unity
  Assets/Scenes/Puzzles/GrapplePullTutorial.unity.meta
Labels: enhancement

#186 Scene changer
  Assets/Bow and Arrow.meta
  Assets/Materials/PaperTextures/paper_lp_lambert1_Normal.png.meta
  Assets/Prefabs/SceneChanger.prefab
  Assets/Prefabs/SceneChanger.prefab.meta
  Assets/Prefabs/SceneChangerEnterance.prefab
  Assets/Prefabs/SceneChangerEnterance.prefab.meta
  Assets/Prefabs/SceneChangerExit.prefab
  Assets/Prefabs/SceneChangerExit.prefab.meta
  Assets/SceneChanger.cs
  Assets/SceneChanger.cs.meta
  Assets/Scenes/SceneChanger1.unity
  Assets/Scenes/SceneChanger1.unity.meta
  Assets/Scenes/SceneChanger2.unity
  Assets/Scenes/SceneChanger2.unity.meta
  Assets/Scripts/DoorActivator.cs
  Assets/Scripts/NewSlidingDoor.cs
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/Packages/com.unity.probuilder/Settings.json
Labels: enhancement

#192 Crate Holder Object
  Assets/Audio/Ambience/Lava.meta
  Assets/Prefabs/Lava.prefab
  Assets/Scenes/Puzzles/GrapplePullTutorial.unity
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/TagManager.asset
Labels: enhancement

#210 Dwarven Language Font
  Assets/Scenes/MainMenu.unity
  Assets/Textures/UI/CREDITS-MENU-BUTTON.png
  Assets/Textures/UI/CREDITS-MENU-BUTTON.png.meta
  Assets/Textures/UI/DWARVESC SDF.asset
  Assets/Textures/UI/DWARVESC SDF.asset.meta
  Assets/Textures/UI/DWARVESC.TTF
  Assets/Textures/UI/DWARVESC.TTF.meta
  Assets/Textures/UI/EXIT-BUTTON.png
  Assets/Textures/UI/EXIT-BUTTON.png.meta
  Assets/Textures/UI/RUNE_2 SDF.asset
  Assets/Textures/UI/RUNE_2 SDF.asset.meta
  Assets/Textures/UI/RUNE_2.TTF
  Assets/Textures/UI/RUNE_2.TTF.meta
  Assets/Textures/UI/START-MENU-BUTTON.png
  Assets/Textures/UI/START-MENU-BUTTON.png.meta
  Assets/Textures/UI/TEXT-ARROWS-GRAPHIC.png
  Assets/Textures/UI/TEXT-ARROWS-GRAPHIC.png.meta
  Assets/Textures/UI/VIDEO-GAME-TITLE.png
  Assets/Textures/UI/VIDEO-GAME-TITLE.png.meta
Labels: documentation

#211 Added Scene Changers
  Assets/Scenes/Puzzles/GrapplePullTutorial.unity
Labels: enhancement

#214 Animated lava
  Assets/Animations/BowDisplay.anim
  Assets/Animations/BowDisplay.anim.meta
  Assets/Animations/bowAnimated Variant.controller
  Assets/Animations/bowAnimated Variant.controller.meta
  Assets/CustomShaders.meta
  Assets/CustomShaders/Black.mat
  Assets/CustomShaders/Black.mat.meta
  Assets/CustomShaders/BlackFade.mat
  Assets/CustomShaders/BlackFade.mat.meta
  Assets/CustomShaders/BlackFade.shader
  Assets/CustomShaders/BlackFade.shader.meta
  Assets/CustomShaders/InfinityMirror.shader
  Assets/CustomShaders/InfinityMirror.shader.meta
  Assets/CustomShaders/Lava.shader
  Assets/CustomShaders/Lava.shader.meta
  Assets/CustomShaders/Lava_Bake.mat
  Assets/CustomShaders/Lava_Bake.mat.meta
  Assets/CustomShaders/Lava_Flowing.mat
  Assets/CustomShaders/Lava_Flowing.mat.meta
  Assets/CustomShaders/Lava_Still.mat
  Assets/CustomShaders/Lava_Still.mat.meta
  Assets/CustomShaders/LightRay.mat
  Assets/CustomShaders/LightRay.mat.meta
  Assets/CustomShaders/LightRay.shader
  Assets/CustomShaders/LightRay.shader.meta
  Assets/CustomShaders/SolidColor.shader
  Assets/CustomShaders/SolidColor.shader.meta
  Assets/CustomShaders/infinityMirror.mat
  Assets/CustomShaders/infinityMirror.mat.meta
  Assets/Music.meta
  Assets/Scenes/AnimatedLava.meta
  Assets/Scenes/AnimatedLava.unity
  Assets/Scenes/AnimatedLava.unity.meta
  Assets/Scenes/AnimatedLava/LightingData.asset
  Assets/Scenes/AnimatedLava/LightingData.asset.meta
  Assets/Scenes/AnimatedLava/Lightmap-0_comp_dir.png
  Assets/Scenes/AnimatedLava/Lightmap-0_comp_dir.png.meta
  Assets/Scenes/AnimatedLava/Lightmap-0_comp_light.exr
  Assets/Scenes/AnimatedLava/Lightmap-0_comp_light.exr.meta
  Assets/Scenes/AnimatedLava/Lightmap-1_comp_dir.png
  Assets/Scenes/AnimatedLava/Lightmap-1_comp_dir.png.meta
  Assets/Scenes/AnimatedLava/Lightmap-1_comp_light.exr
  Assets/Scenes/AnimatedLava/Lightmap-1_comp_light.exr.meta
  Assets/Scenes/AnimatedLava/Main Camera Profile.asset
  Assets/Scenes/AnimatedLava/Main Camera Profile.asset.meta
  Assets/Settings/UniversalRP-HighQuality.asset
  Assets/Settings/UniversalRP-LowQuality.asset
  Assets/Settings/UniversalRP-MediumQuality.asset
  Assets/_DwarvenRuins/Materials/DwarvenRuinesKrystall.mat
  Assets/_DwarvenRuins/Meshes/Decor.FBX.meta
  Assets/_DwarvenRuins/Meshes/DwarvenRuins1.FBX.meta
  Assets/_DwarvenRuins/Meshes/DwarvenRuinsGathered.FBX.meta
  Assets/_DwarvenRuins/Meshes/DwarvenRuinsGathered2.FBX.meta
  Assets/_DwarvenRuins/Meshes/DwarvenRuinsWalls.FBX.meta
  Assets/_DwarvenRuins/Meshes/Krystall.FBX.meta
  ProjectSettings/Packages/com.unity.probuilder/Settings.json
Labels: enhancement

#228 2 d assets
  Assets/Arts.meta
  Assets/Arts/Slider.meta
  Assets/Arts/Slider/Slider Bar.png
  Assets/Arts/Slider/Slider Bar.png.meta
  Assets/Arts/Slider/Slider Circle.png
  Assets/Arts/Slider/Slider Circle.png.meta
  Assets/Arts/Slider/Slider.clip
  Assets/Arts/Slider/Slider.clip.meta
  Assets/Arts/paper texture.png
  Assets/Arts/paper texture.png.meta
  Assets/Original Meshes/New folder.meta
  Assets/Prefabs/Slider Prefab.prefab
  Assets/Prefabs/Slider Prefab.prefab.meta
Labels: enhancement

#216 Archer puzzles
  Assets/Scenes/Puzzles/GauntletTutorial.meta
  Assets/Scenes/Puzzles/GauntletTutorial.unity
  Assets/Scenes/Puzzles/GauntletTutorial.unity.meta
  Assets/Scenes/Puzzles/GauntletTutorial/LightingData.asset
  Assets/Scenes/Puzzles/GauntletTutorial/LightingData.asset.meta
  Assets/Scenes/Puzzles/GauntletTutorial/ReflectionProbe-0.exr
  Assets/Scenes/Puzzles/GauntletTutorial/ReflectionProbe-0.exr.meta
  Assets/Scenes/Puzzles/GauntletTutorial/ReflectionProbe-1.exr
  Assets/Scenes/Puzzles/GauntletTutorial/ReflectionProbe-1.exr.meta
  Assets/Scenes/Puzzles/GauntletTutorial/ReflectionProbe-2.exr
  Assets/Scenes/Puzzles/GauntletTutorial/ReflectionProbe-2.exr.meta
  Assets/Scenes/Puzzles/GauntletTutorial/ReflectionProbe-3.exr
  Assets/Scenes/Puzzles/GauntletTutorial/ReflectionProbe-3.exr.meta
Labels: enhancement
