Repository AztecGameLab/LongTermGame4, pull requests merged in 2020-10, with the labels that each got.

#28 Fixed Commit that broke everything
  ThePeople/Jacob.Golden-Needham.txt
Labels: bug

#42 Github Demo text document
  GitHub Documentation/Demo.txt
Labels: documentation

#44 Add Camera Shake Effect
  Assets/Scenes/ScreenShakeDemo.unity
  Assets/Scenes/ScreenShakeDemo.unity.meta
  Assets/Scripts/CameraFX.cs
  Assets/Scripts/CameraFX.cs.meta
  Assets/Scripts/TestPlayer.cs
  Assets/Scripts/TestPlayer.cs.meta
  Packages/packages-lock.json
Labels: enhancement

#40 Arrow triggered button
  Assets/Materials/New Material.mat
  Assets/Materials/New Material.mat.meta
  Assets/Prefabs/Arrow.prefab
  Assets/Prefabs/ArrowButton.prefab
  Assets/Prefabs/ArrowButton.prefab.meta
  Assets/Scenes/ArrowTriggeredButton.unity
  Assets/Scenes/ArrowTriggeredButton.unity.meta
  Assets/Scripts/ArrowTriggeredButton.cs
  Assets/Scripts/ArrowTriggeredButton.cs.meta
  Packages/packages-lock.json
  ProjectSettings/TagManager.asset
Labels: enhancement

#46 Player movement
  .DS_Store
  Assets/Scenes/PlayerMovement.unity
  Assets/Scenes/PlayerMovement.unity.meta
  Assets/Scripts/Looking.cs
  Assets/Scripts/Looking.cs.meta
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/PlayerMovement.cs.meta
  ProjectSettings/TagManager.asset
Labels: enhancement

#47 Fixing the package-lock problem
  .gitignore
Labels: bug

#48 Main menu
  Assets/Scenes/MainMenu.unity
  Assets/Scenes/MainMenu.unity.meta
  Assets/Scenes/Play.unity
  Assets/Scenes/Play.unity.meta
  Assets/Scripts/ButtonManager.cs
  Assets/Scripts/ButtonManager.cs.meta
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#49 Sliding door
  Assets/Animations.meta
  Assets/Scenes/SlidingDoorScene.unity
  Assets/Scenes/SlidingDoorScene.unity.meta
  Assets/Scripts/SlidingDoor.cs
  Assets/Scripts/SlidingDoor.cs.meta
  ProjectSettings/QualitySettings.asset
Labels: enhancement

#67 Created a test text file
  ThePeople/MBTest1.txt
Labels: wontfix

#66 Added a cool test file.
  ThePeople/DanielTest2.txt
Labels: wontfix

#64 This is a test
  ThePeople/KMKTest1.txt
Labels: wontfix

#71 Player singleton, player prefab and combined work scene
  Assets/Materials/GenericBlue.mat
  Assets/Materials/GenericBlue.mat.meta
  Assets/Materials/GenericRed.mat
  Assets/Materials/GenericRed.mat.meta
  Assets/PlayerManager.cs
  Assets/PlayerManager.cs.meta
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Player.prefab.meta
  Assets/Scenes/CombinedScene.unity
  Assets/Scenes/CombinedScene.unity.meta
  ProjectSettings/QualitySettings.asset
Labels: enhancement

#73 Bow and arrows
  Assets/Audio/Arrows/Arrow_Hit_Wall.wav
  Assets/Audio/Arrows/Fire_Bow_Shot.wav
  Assets/Audio/Arrows/Ice_Bow_Shot.wav
  Assets/Audio/Arrows/Raw_Bow_Shot.wav
  Assets/Audio/Bow/Magic_Bow_Stretch.wav
  Assets/Audio/Bow/Raw_Bow_Stretch.wav
Labels: enhancement

#76 Grappling hook
  Assets/Prefabs/Grappling(Sticky)Arrow Variant.prefab
  Assets/Prefabs/Grappling(Sticky)Arrow Variant.prefab.meta
  Assets/Scenes/CombinedScene.unity
  Assets/Scripts/GrapplingArrow.cs
  Assets/Scripts/GrapplingArrow.cs.meta
  Packages/packages-lock.json
  ProjectSettings/QualitySettings.asset
Labels: enhancement

#77 Player velocity bug fix
  Assets/Prefabs/Player.prefab
  Assets/Scripts/PlayerMovement.cs
Labels: bug

#83 Arrow unity events
  Assets/Audio.meta
  Assets/Audio/Ambience.meta
  Assets/Audio/Ambience/AGL_Ambience.wav.meta
  Assets/Audio/Arrows.meta
  Assets/Audio/Arrows/Arrow_Hit_Wall.wav.meta
  Assets/Audio/Arrows/Fire_Bow_Shot.wav.meta
  Assets/Audio/Arrows/Ice_Bow_Shot.wav.meta
  Assets/Audio/Arrows/Raw_Bow_Shot.wav.meta
  Assets/Audio/Bow.meta
  Assets/Audio/Bow/Magic_Bow_Stretch.wav.meta
  Assets/Audio/Bow/Raw_Bow_Stretch.wav.meta
  Assets/Materials/GenericWhite.mat
  Assets/Materials/GenericWhite.mat.meta
  Assets/Scenes/ArrowTriggerTesting.unity
  Assets/Scenes/ArrowTriggerTesting.unity.meta
  Assets/Scenes/CombinedScene.unity
  Assets/Scripts/ArrowTrigger.cs
  Assets/Scripts/ArrowTrigger.cs.meta
  Assets/Scripts/ArrowTriggeredIndicator.cs
  Assets/Scripts/ArrowTriggeredIndicator.cs.meta
  Packages/packages-lock.json
Labels: enhancement

#45 Player shooting
  Assets/Scenes/PlayerShooting.unity
  Assets/Scripts/PlayerShooting.cs
Labels: enhancement

#111 Stick arrow bug fixes
  Assets/Music.meta
  Assets/Music/Ethereal Sample.wav.meta
  Assets/Prefabs/Arrows/StickyArrow.prefab
  Assets/Scripts/ArrowScript.cs
  Assets/Scripts/StickyArrowScript.cs
  Assets/Scripts/StickyArrowScript.cs.meta
Labels: bug

#118 Fixes to the parenting problem
  Assets/Scenes/ArrowStickInWall.unity
  Assets/Scripts/StickyArrowScript.cs
  Packages/packages-lock.json
Labels: bug

#116 implenting audio and making changes to the player prefab
  Assets/Audio/Main Mixer.mixer
  Assets/Prefabs/Arrows/ArrowCombined.prefab
  Assets/Prefabs/Arrows/ArrowCombined.prefab.meta
  Assets/Prefabs/Player.prefab
  Assets/Scenes/CombinedScene.unity
  Assets/Scripts/PlayerManager.cs
  ProjectSettings/QualitySettings.asset
Labels: enhancement

#120 UI reticle
  Assets/Music/Ominous Classical Guitar Sample.wav.meta
  Assets/Prefabs/Reticle.prefab
  Assets/Prefabs/Reticle.prefab.meta
  Assets/Scenes/PlayerMovement.unity
  ProjectSettings/Packages/com.unity.progrids/Settings.json
Labels: enhancement

#123 4 different shatter sound effects
  Assets/Audio/Arrows/Collisions/Magical Shatter.wav
  Assets/Audio/Arrows/Collisions/Mid Aggressive Shatter.wav
  Assets/Audio/Arrows/Collisions/Quick Treble Shatter.wav
  Assets/Audio/Arrows/Collisions/Very Aggressive Shatter.wav
Labels: enhancement

#125 Pick up objects
  Assets/Audio/Arrows/Collisions.meta
  Assets/Audio/Arrows/Collisions/Magical Shatter.wav.meta
  Assets/Audio/Arrows/Collisions/Mid Aggressive Shatter.wav.meta
  Assets/Audio/Arrows/Collisions/Quick Treble Shatter.wav.meta
  Assets/Audio/Arrows/Collisions/Very Aggressive Shatter.wav.meta
  Assets/Audio/Movement.meta
  Assets/Audio/Movement/Thud.asset
  Assets/Audio/Movement/Thud.asset.meta
  Assets/Audio/Movement/thud.wav
  Assets/Audio/Movement/thud.wav.meta
  Assets/Scenes/PickupObjects.unity
  Assets/Scenes/PickupObjects.unity.meta
  Assets/Scripts/Audio Scripts/Sound.cs
  Assets/Scripts/InteractHoldable.cs
  Assets/Scripts/InteractHoldable.cs.meta
  Assets/Scripts/InteractUnityEvent.cs
  Assets/Scripts/InteractUnityEvent.cs.meta
  Assets/Scripts/Interactable.cs
  Assets/Scripts/Interactable.cs.meta
  Assets/Scripts/PlayerInteract.cs
  Assets/Scripts/PlayerInteract.cs.meta
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/Packages/com.unity.probuilder/Settings.json
Labels: enhancement

#127 Rock Door
  Assets/Audio/Doors/Rock Door.wav
Labels: enhancement

#136 Pick up objects patch
  Assets/Music/Curtain_Call.wav.meta
  Assets/Music/Curtain_Call_FINALIZED.wav.meta
  Assets/Music/Mystic_Energy.wav.meta
  Assets/Scenes/PickupObjects.unity
  Assets/Scripts/Holdable Settings.meta
  Assets/Scripts/Holdable Settings/Default.asset
  Assets/Scripts/Holdable Settings/Default.asset.meta
  Assets/Scripts/Holdable Settings/Example Box.asset
  Assets/Scripts/Holdable Settings/Example Box.asset.meta
  Assets/Scripts/HoldableSettings.cs
  Assets/Scripts/HoldableSettings.cs.meta
  Assets/Scripts/InteractHoldable.cs
  Assets/Scripts/InteractHoldable.cs.meta
  Assets/Scripts/PlayerInteract.cs
  ProjectSettings/QualitySettings.asset
Labels: bug

#146 Adding in Basic Bow and Arrow
  Assets/Bow and Arrow/Bow.fbx
  Assets/Bow and Arrow/arrow.fbx
Labels: enhancement
